# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
import re
from openapi_server import util

import re  # noqa: E501

class LateBorrowersLate(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, book=None, date_of_return=None):  # noqa: E501
        """LateBorrowersLate - a model defined in OpenAPI

        :param book: The book of this LateBorrowersLate.  # noqa: E501
        :type book: str
        :param date_of_return: The date_of_return of this LateBorrowersLate.  # noqa: E501
        :type date_of_return: date
        """
        self.openapi_types = {
            'book': str,
            'date_of_return': date
        }

        self.attribute_map = {
            'book': 'book',
            'date_of_return': 'date_of_return'
        }

        self._book = book
        self._date_of_return = date_of_return

    @classmethod
    def from_dict(cls, dikt) -> 'LateBorrowersLate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The late_borrowers_late of this LateBorrowersLate.  # noqa: E501
        :rtype: LateBorrowersLate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def book(self):
        """Gets the book of this LateBorrowersLate.


        :return: The book of this LateBorrowersLate.
        :rtype: str
        """
        return self._book

    @book.setter
    def book(self, book):
        """Sets the book of this LateBorrowersLate.


        :param book: The book of this LateBorrowersLate.
        :type book: str
        """

        self._book = book

    @property
    def date_of_return(self):
        """Gets the date_of_return of this LateBorrowersLate.


        :return: The date_of_return of this LateBorrowersLate.
        :rtype: date
        """
        return self._date_of_return

    @date_of_return.setter
    def date_of_return(self, date_of_return):
        """Sets the date_of_return of this LateBorrowersLate.


        :param date_of_return: The date_of_return of this LateBorrowersLate.
        :type date_of_return: date
        """
        if date_of_return is not None and not re.search(r'([0-9]{4})-(?:[0-9]{2})-([0-9]{2})', date_of_return):  # noqa: E501
            raise ValueError("Invalid value for `date_of_return`, must be a follow pattern or equal to `/([0-9]{4})-(?:[0-9]{2})-([0-9]{2})/`")  # noqa: E501

        self._date_of_return = date_of_return
